import Navigation from "@/components/Navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Link } from "react-router-dom";
import { useEffect } from "react";

const BlogSupplyDistribution = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      
      {/* Hero Section */}
      <div className="bg-gradient-to-br from-secondary via-background to-accent-light">
        <div className="max-w-4xl mx-auto px-6 py-16">
          <div className="text-center space-y-6">
            <Badge className="bg-accent-light text-accent-foreground text-lg px-4 py-2">
              Blog
            </Badge>
            <h1 className="text-4xl md:text-5xl font-bold text-primary">
              Supply vs. Distribution and Demand Charges – Decoding Your Utility Bill
            </h1>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              Understand the difference between supply and distribution charges, learn how demand charges work and discover strategies to reduce these costs across multiple business locations.
            </p>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-4xl mx-auto px-6 py-16">
        <div className="prose prose-lg max-w-none">
          <div className="space-y-12">
            
            {/* Introduction */}
            <section>
              <p className="text-lg text-muted-foreground leading-relaxed">
                If you've ever looked at an electricity or gas invoice and wondered why there are separate line items for <strong>supply</strong> and <strong>distribution</strong>, you're not alone. These distinctions can be confusing, yet they are crucial for managing energy costs—especially for organizations with multiple sites. This article breaks down what each term means, explains how demand charges are calculated and offers practical tips for controlling these costs.
              </p>
            </section>

            {/* Supply vs. distribution: two halves of your bill */}
            <section>
              <h2 className="text-3xl font-bold text-primary mb-6">Supply vs. distribution: two halves of your bill</h2>
              <p className="text-muted-foreground mb-4">
                <strong>Supply charges</strong> cover the cost of the energy itself—the electricity generated by power plants or the natural gas delivered from producers. In deregulated markets, you can shop around for this portion through competitive suppliers. <strong>Distribution charges</strong> (sometimes called delivery charges) pay for the poles, wires, transformers, pipelines, metering and customer service required to bring that energy to your facility.
              </p>
              <p className="text-muted-foreground mb-6">
                A typical electricity bill splits roughly 45% to supply and 55% to delivery. Some utilities list these items separately, while others roll them into a single bundled rate.
              </p>
              <p className="text-muted-foreground">
                Within the distribution portion, many regulators require the utility to recover costs through two types of charges: a <strong>volumetric rate</strong> based on the amount of energy delivered and a <strong>fixed customer charge</strong> that appears on the bill regardless of usage. The supply portion, by contrast, is measured in kWh or therms consumed, and in deregulated regions you can negotiate this rate through a third‑party supplier.
              </p>
            </section>

            {/* Introducing demand charges */}
            <section>
              <h2 className="text-3xl font-bold text-primary mb-6">Introducing demand charges</h2>
              <p className="text-muted-foreground mb-4">
                While energy and delivery charges are relatively straightforward, <strong>demand charges</strong> can catch businesses off‑guard. Utilities must maintain enough generation and transmission capacity to meet their customers' highest instantaneous power needs. To recoup these capital costs, many tariffs include a demand charge based on the customer's <strong>highest 15‑ or 30‑minute interval</strong> of electricity use during the billing cycle.
              </p>
              <p className="text-muted-foreground">
                The charge is calculated by multiplying this peak demand in kilowatts (kW) by a fixed rate. Even if you use very little power on average, a short surge—starting up a large machine or turning on multiple HVAC units at once—can result in a high demand charge that persists for months.
              </p>
              <div className="bg-accent/10 p-6 rounded-lg mt-6">
                <p className="text-muted-foreground">
                  <strong>Important:</strong> Demand charges can represent a substantial portion of commercial and industrial electric bills. Because some tariffs include <strong>demand ratchets</strong> (where a single peak sets a minimum billing demand for several months) or <strong>multiple demand periods</strong> (on‑peak, off‑peak and shoulder), understanding how they work is critical to selecting the right tariff and operating efficiently.
                </p>
              </div>
            </section>

            {/* Strategies to manage supply, distribution and demand costs */}
            <section>
              <h2 className="text-3xl font-bold text-primary mb-6">Strategies to manage supply, distribution and demand costs</h2>
              
              <div className="space-y-8">
                {/* Strategy 1 */}
                <Card>
                  <CardContent className="p-6">
                    <h3 className="text-2xl font-bold text-primary mb-4">1. Review your tariff</h3>
                    <p className="text-muted-foreground mb-4">
                      Different rate schedules allocate charges differently. Some prioritize energy charges, while others emphasize demand or delivery costs. With more than 11,000 rate structures in North America, there may be a better fit for your usage profile.
                    </p>
                    <p className="text-muted-foreground">
                      Conducting a tariff analysis for each location shows what you would pay under alternative rates and helps identify the optimal structure.
                    </p>
                  </CardContent>
                </Card>

                {/* Strategy 2 */}
                <Card>
                  <CardContent className="p-6">
                    <h3 className="text-2xl font-bold text-primary mb-4">2. Compare supply options</h3>
                    <p className="text-muted-foreground">
                      In deregulated markets, you are not locked into the utility's default supply rate. Competitive suppliers offer fixed or index‑based pricing, and some include transmission or capacity costs that would otherwise appear on your distribution bill. Understanding how the supplier's rate interacts with the distribution tariff is vital for an apples‑to‑apples comparison.
                    </p>
                  </CardContent>
                </Card>

                {/* Strategy 3 */}
                <Card>
                  <CardContent className="p-6">
                    <h3 className="text-2xl font-bold text-primary mb-4">3. Manage peak demand</h3>
                    <div className="space-y-4">
                      <div className="flex items-start space-x-3">
                        <div className="w-2 h-2 bg-accent rounded-full mt-3 flex-shrink-0"></div>
                        <div>
                          <h4 className="font-semibold text-primary mb-1">Stagger equipment start‑ups</h4>
                          <p className="text-muted-foreground">Avoid turning on large loads simultaneously. Instead, sequence processes or use soft‑start devices to reduce instantaneous demand.</p>
                        </div>
                      </div>
                      
                      <div className="flex items-start space-x-3">
                        <div className="w-2 h-2 bg-accent rounded-full mt-3 flex-shrink-0"></div>
                        <div>
                          <h4 className="font-semibold text-primary mb-1">Install demand management controls</h4>
                          <p className="text-muted-foreground">Advanced energy management systems or battery storage can smooth out peaks by shedding non‑essential loads or discharging stored energy when demand spikes. These investments may be justified if demand charges make up a large part of your bill.</p>
                        </div>
                      </div>
                      
                      <div className="flex items-start space-x-3">
                        <div className="w-2 h-2 bg-accent rounded-full mt-3 flex-shrink-0"></div>
                        <div>
                          <h4 className="font-semibold text-primary mb-1">Consider alternative tariffs</h4>
                          <p className="text-muted-foreground">Time‑of‑use or critical‑peak tariffs sometimes lower demand charges in exchange for higher energy rates during certain hours. Modeling your load profile under different options reveals whether shifting usage would save money.</p>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* Strategy 4 */}
                <Card>
                  <CardContent className="p-6">
                    <h3 className="text-2xl font-bold text-primary mb-4">4. Address non‑commodity costs</h3>
                    <p className="text-muted-foreground mb-4">
                      Transmission, distribution and other non‑commodity charges can exceed half of your total energy cost. Programs like power factor correction, participation in demand response, or opting for interruptible service can reduce these fees.
                    </p>
                    <p className="text-muted-foreground">
                                             Industry best practices recommend regularly reviewing non‑commodity charges and exploring alternative tariffs.
                    </p>
                  </CardContent>
                </Card>

                {/* Strategy 5 */}
                <Card>
                  <CardContent className="p-6">
                    <h3 className="text-2xl font-bold text-primary mb-4">5. Seek expert help tailored to mid‑size organizations</h3>
                    <p className="text-muted-foreground mb-4">
                                             Enterprise‑level energy management firms often cater to very large corporations, leaving mid‑size organizations with limited support. Feroz Energy bridges this gap by combining proven practices:
                    </p>
                    <ul className="text-muted-foreground space-y-2 ml-6">
                                             <li>• Comprehensive bill auditing and analysis</li>
                       <li>• Data‑driven rate comparisons using advanced algorithms</li>
                       <li>• Systematic assessment of non‑commodity costs and alternative tariffs</li>
                    </ul>
                    <p className="text-muted-foreground mt-4">
                      We evaluate supply and distribution tariffs together, help manage demand and provide actionable recommendations.
                    </p>
                  </CardContent>
                </Card>
              </div>
            </section>

            {/* Conclusion */}
            <section>
              <h2 className="text-3xl font-bold text-primary mb-6">Conclusion</h2>
              <p className="text-lg text-muted-foreground">
                                 Understanding the differences between supply and distribution charges, and grasping how demand charges work, is the first step to controlling energy expenses. By reviewing tariffs, comparing supply options and managing peaks, multi‑site businesses can significantly reduce costs. If you're ready to take a closer look at your bills, Feroz Energy can guide you through the process and identify opportunities you might be missing.
              </p>
            </section>

            {/* CTA Section */}
            <section className="text-center bg-gradient-to-r from-accent/10 to-accent-light/10 p-12 rounded-lg">
              <h2 className="text-3xl font-bold text-primary mb-6">Ready to decode your utility bills?</h2>
              <p className="text-lg text-muted-foreground mb-8 max-w-2xl mx-auto">
                                 Let Feroz Energy help you understand your utility charges and identify opportunities to reduce costs across your multi-site organization.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Button asChild size="lg" className="bg-gradient-accent hover:opacity-90">
                  <Link to="/">Get Started</Link>
                </Button>
                <Button asChild variant="outline" size="lg">
                  <Link to="/learn-more">About Us</Link>
                </Button>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BlogSupplyDistribution;
